site_name: Voxel51 Documentation
theme:
  name: material
repo_url: https://github.com/thesteve0/vdoc-mkdocs
markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:      
      line_spans: __span
      pygments_lang_class: true

